[2025-07-07T02:13:43.869+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-07T02:13:43.977+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_spark_inline.spark_write_data manual__2025-07-07T02:06:22.209511+00:00 [queued]>
[2025-07-07T02:13:43.981+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_spark_inline.spark_write_data manual__2025-07-07T02:06:22.209511+00:00 [queued]>
[2025-07-07T02:13:43.981+0000] {taskinstance.py:2303} INFO - Starting attempt 3 of 3
[2025-07-07T02:13:43.995+0000] {taskinstance.py:2327} INFO - Executing <Task(SparkSubmitOperator): spark_write_data> on 2025-07-07 02:06:22.209511+00:00
[2025-07-07T02:13:43.999+0000] {standard_task_runner.py:63} INFO - Started process 3619 to run task
[2025-07-07T02:13:44.001+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'my_spark_inline', 'spark_write_data', 'manual__2025-07-07T02:06:22.209511+00:00', '--job-id', '98', '--raw', '--subdir', 'DAGS_FOLDER/test_spark.py', '--cfg-path', '/tmp/tmpy7m5n5lv']
[2025-07-07T02:13:44.002+0000] {standard_task_runner.py:91} INFO - Job 98: Subtask spark_write_data
[2025-07-07T02:13:44.019+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.11/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-07-07T02:13:44.042+0000] {task_command.py:426} INFO - Running <TaskInstance: my_spark_inline.spark_write_data manual__2025-07-07T02:06:22.209511+00:00 [running]> on host 40aa9e29f527
[2025-07-07T02:13:44.094+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='my_spark_inline' AIRFLOW_CTX_TASK_ID='spark_write_data' AIRFLOW_CTX_EXECUTION_DATE='2025-07-07T02:06:22.209511+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-07T02:06:22.209511+00:00'
[2025-07-07T02:13:44.094+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-07T02:13:44.110+0000] {base.py:84} INFO - Using connection ID 'spark-master' for task execution.
[2025-07-07T02:13:44.112+0000] {spark_submit.py:473} INFO - Spark-Submit cmd: spark-submit --master spark-master:7077 --packages com.clickhouse:clickhouse-jdbc:0.6.4,org.apache.httpcomponents.client5:httpclient5:5.3.1,org.apache.hadoop:hadoop-aws:3.3.1,com.amazonaws:aws-java-sdk-bundle:1.11.1026 --name arrow-spark --deploy-mode client /opt/***/spark_project/src/spark/spark_main_minio.py
[2025-07-07T02:13:44.318+0000] {spark_submit.py:634} INFO - WARNING: Using incubator modules: jdk.incubator.vector
[2025-07-07T02:13:45.623+0000] {spark_submit.py:634} INFO - :: loading settings :: url = jar:file:/home/***/.local/lib/python3.11/site-packages/pyspark/jars/ivy-2.5.3.jar!/org/apache/ivy/core/settings/ivysettings.xml
[2025-07-07T02:13:45.705+0000] {spark_submit.py:634} INFO - Ivy Default Cache set to: /home/***/.ivy2.5.2/cache
[2025-07-07T02:13:45.706+0000] {spark_submit.py:634} INFO - The jars for the packages stored in: /home/***/.ivy2.5.2/jars
[2025-07-07T02:13:45.708+0000] {spark_submit.py:634} INFO - com.clickhouse#clickhouse-jdbc added as a dependency
[2025-07-07T02:13:45.708+0000] {spark_submit.py:634} INFO - org.apache.httpcomponents.client5#httpclient5 added as a dependency
[2025-07-07T02:13:45.708+0000] {spark_submit.py:634} INFO - org.apache.hadoop#hadoop-aws added as a dependency
[2025-07-07T02:13:45.708+0000] {spark_submit.py:634} INFO - com.amazonaws#aws-java-sdk-bundle added as a dependency
[2025-07-07T02:13:45.708+0000] {spark_submit.py:634} INFO - :: resolving dependencies :: org.apache.spark#spark-submit-parent-2469c417-d9e2-4631-8a76-45853a36c62f;1.0
[2025-07-07T02:13:45.708+0000] {spark_submit.py:634} INFO - confs: [default]
[2025-07-07T02:13:45.888+0000] {spark_submit.py:634} INFO - found com.clickhouse#clickhouse-jdbc;0.6.4 in central
[2025-07-07T02:13:45.904+0000] {spark_submit.py:634} INFO - found org.apache.httpcomponents.client5#httpclient5;5.3.1 in central
[2025-07-07T02:13:45.917+0000] {spark_submit.py:634} INFO - found org.apache.httpcomponents.core5#httpcore5;5.2.4 in central
[2025-07-07T02:13:45.990+0000] {spark_submit.py:634} INFO - found org.apache.httpcomponents.core5#httpcore5-h2;5.2.4 in central
[2025-07-07T02:13:46.000+0000] {spark_submit.py:634} INFO - found org.slf4j#slf4j-api;1.7.36 in central
[2025-07-07T02:13:53.654+0000] {spark_submit.py:634} INFO - found org.apache.hadoop#hadoop-aws;3.3.1 in central
[2025-07-07T02:13:56.342+0000] {spark_submit.py:634} INFO - found org.wildfly.openssl#wildfly-openssl;1.0.7.Final in central
[2025-07-07T02:13:58.987+0000] {spark_submit.py:634} INFO - found com.amazonaws#aws-java-sdk-bundle;1.11.1026 in central
[2025-07-07T02:13:59.481+0000] {spark_submit.py:634} INFO - downloading https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-aws/3.3.1/hadoop-aws-3.3.1.jar ...
[2025-07-07T02:14:00.874+0000] {spark_submit.py:634} INFO - [SUCCESSFUL ] org.apache.hadoop#hadoop-aws;3.3.1!hadoop-aws.jar (1881ms)
[2025-07-07T02:14:01.095+0000] {spark_submit.py:634} INFO - downloading https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-bundle/1.11.1026/aws-java-sdk-bundle-1.11.1026.jar ...
[2025-07-07T02:44:09.786+0000] {local_task_job_runner.py:288} WARNING - Recorded pid 4672 does not match the current pid 3619
[2025-07-07T02:44:09.787+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-07-07T02:44:09.789+0000] {process_utils.py:132} INFO - Sending 15 to group 3619. PIDs of all processes in the group: [3620, 3619]
[2025-07-07T02:44:09.789+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 3619
[2025-07-07T02:44:09.789+0000] {taskinstance.py:2607} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-07-07T02:44:09.789+0000] {spark_submit.py:760} INFO - Sending kill signal to spark-submit
[2025-07-07T02:44:09.790+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-07T02:44:09.797+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 176, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 548, in submit
    self._process_spark_submit_log(iter(self._submit_sp.stdout))  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 597, in _process_spark_submit_log
    for line in itr:
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 2609, in signal_handler
    raise AirflowTaskTerminated("Task received SIGTERM signal")
airflow.exceptions.AirflowTaskTerminated: Task received SIGTERM signal
[2025-07-07T02:44:09.799+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=my_spark_inline, task_id=spark_write_data, execution_date=20250707T020622, start_date=20250707T024409, end_date=20250707T024409
[2025-07-07T02:44:09.815+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=3620, status='terminated', started='02:13:43') (3620) terminated with exit code None
[2025-07-07T02:44:09.816+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=3619, status='terminated', exitcode=2, started='02:13:43') (3619) terminated with exit code 2
