[2025-07-07T03:10:40.439+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-07T03:10:40.551+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_spark_inline.spark_write_data manual__2025-07-07T02:06:22.209511+00:00 [queued]>
[2025-07-07T03:10:40.558+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_spark_inline.spark_write_data manual__2025-07-07T02:06:22.209511+00:00 [queued]>
[2025-07-07T03:10:40.558+0000] {taskinstance.py:2303} INFO - Starting attempt 8 of 8
[2025-07-07T03:10:40.573+0000] {taskinstance.py:2327} INFO - Executing <Task(SparkSubmitOperator): spark_write_data> on 2025-07-07 02:06:22.209511+00:00
[2025-07-07T03:10:40.577+0000] {standard_task_runner.py:63} INFO - Started process 6165 to run task
[2025-07-07T03:10:40.579+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'my_spark_inline', 'spark_write_data', 'manual__2025-07-07T02:06:22.209511+00:00', '--job-id', '103', '--raw', '--subdir', 'DAGS_FOLDER/test_spark.py', '--cfg-path', '/tmp/tmp0on1gdhv']
[2025-07-07T03:10:40.581+0000] {standard_task_runner.py:91} INFO - Job 103: Subtask spark_write_data
[2025-07-07T03:10:40.592+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.11/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-07-07T03:10:40.612+0000] {task_command.py:426} INFO - Running <TaskInstance: my_spark_inline.spark_write_data manual__2025-07-07T02:06:22.209511+00:00 [running]> on host 40aa9e29f527
[2025-07-07T03:10:40.662+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='my_spark_inline' AIRFLOW_CTX_TASK_ID='spark_write_data' AIRFLOW_CTX_EXECUTION_DATE='2025-07-07T02:06:22.209511+00:00' AIRFLOW_CTX_TRY_NUMBER='8' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-07T02:06:22.209511+00:00'
[2025-07-07T03:10:40.663+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-07T03:10:40.676+0000] {base.py:84} INFO - Using connection ID 'spark-master' for task execution.
[2025-07-07T03:10:40.676+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-07T03:10:40.676+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 176, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 532, in submit
    spark_submit_cmd = self._build_spark_submit_command(application)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 473, in _build_spark_submit_command
    self.log.info("Spark-Submit cmd: %s", self._mask_cmd(connection_cmd))
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 377, in _mask_cmd
    " ".join(connection_cmd),
    ^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: sequence item 20: expected str instance, list found
[2025-07-07T03:10:40.683+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=my_spark_inline, task_id=spark_write_data, execution_date=20250707T020622, start_date=20250707T031040, end_date=20250707T031040
[2025-07-07T03:10:40.689+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 103 for task spark_write_data (sequence item 20: expected str instance, list found; 6165)
[2025-07-07T03:10:40.711+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-07-07T03:10:40.721+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-07T03:10:40.722+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
