[2025-07-03T13:03:04.011+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-03T13:03:04.034+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: simple_minio_check.check_minio_connection manual__2025-07-03T13:03:03.147481+00:00 [queued]>
[2025-07-03T13:03:04.038+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: simple_minio_check.check_minio_connection manual__2025-07-03T13:03:03.147481+00:00 [queued]>
[2025-07-03T13:03:04.038+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2025-07-03T13:03:04.045+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): check_minio_connection> on 2025-07-03 13:03:03.147481+00:00
[2025-07-03T13:03:04.049+0000] {standard_task_runner.py:63} INFO - Started process 691 to run task
[2025-07-03T13:03:04.052+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'simple_minio_check', 'check_minio_connection', 'manual__2025-07-03T13:03:03.147481+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/test_connection_to_minio.py', '--cfg-path', '/tmp/tmpnjsxjbma']
[2025-07-03T13:03:04.053+0000] {standard_task_runner.py:91} INFO - Job 7: Subtask check_minio_connection
[2025-07-03T13:03:04.063+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.11/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-07-03T13:03:04.087+0000] {task_command.py:426} INFO - Running <TaskInstance: simple_minio_check.check_minio_connection manual__2025-07-03T13:03:03.147481+00:00 [running]> on host 8cef375d7ad3
[2025-07-03T13:03:04.133+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='simple_minio_check' AIRFLOW_CTX_TASK_ID='check_minio_connection' AIRFLOW_CTX_EXECUTION_DATE='2025-07-03T13:03:03.147481+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-03T13:03:03.147481+00:00'
[2025-07-03T13:03:04.133+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-03T13:03:04.140+0000] {logging_mixin.py:188} INFO - üîç Starting MinIO connection check...
[2025-07-03T13:03:04.267+0000] {logging_mixin.py:188} INFO - ‚úÖ MinIO client created successfully
[2025-07-03T13:03:04.267+0000] {logging_mixin.py:188} INFO - 
üì¶ Testing bucket access...
[2025-07-03T13:03:04.384+0000] {logging_mixin.py:188} INFO - ‚ùå Error listing buckets: An error occurred (InvalidArgument) when calling the ListBuckets operation: S3 API Requests must be made to API port.
[2025-07-03T13:03:04.385+0000] {python.py:237} INFO - Done. Returned value was: False
[2025-07-03T13:03:04.385+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-03T13:03:04.408+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=simple_minio_check, task_id=check_minio_connection, execution_date=20250703T130303, start_date=20250703T130304, end_date=20250703T130304
[2025-07-03T13:03:04.423+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-07-03T13:03:04.441+0000] {taskinstance.py:3482} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-07-03T13:03:04.442+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
