[2025-07-07T07:16:46.537+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-07T07:16:46.556+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: minio_ga4_new_file_detector.branch_if_new_data manual__2025-07-07T06:53:38.076557+00:00 [queued]>
[2025-07-07T07:16:46.561+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: minio_ga4_new_file_detector.branch_if_new_data manual__2025-07-07T06:53:38.076557+00:00 [queued]>
[2025-07-07T07:16:46.561+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2025-07-07T07:16:46.567+0000] {taskinstance.py:2327} INFO - Executing <Task(BranchPythonOperator): branch_if_new_data> on 2025-07-07 06:53:38.076557+00:00
[2025-07-07T07:16:46.608+0000] {standard_task_runner.py:63} INFO - Started process 3686 to run task
[2025-07-07T07:16:46.612+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'minio_ga4_new_file_detector', 'branch_if_new_data', 'manual__2025-07-07T06:53:38.076557+00:00', '--job-id', '148', '--raw', '--subdir', 'DAGS_FOLDER/dag_automatic.py', '--cfg-path', '/tmp/tmp0a6gkves']
[2025-07-07T07:16:46.614+0000] {standard_task_runner.py:91} INFO - Job 148: Subtask branch_if_new_data
[2025-07-07T07:16:46.623+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.11/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-07-07T07:16:46.645+0000] {task_command.py:426} INFO - Running <TaskInstance: minio_ga4_new_file_detector.branch_if_new_data manual__2025-07-07T06:53:38.076557+00:00 [running]> on host 34b334fe6b50
[2025-07-07T07:16:46.739+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='minio_ga4_new_file_detector' AIRFLOW_CTX_TASK_ID='branch_if_new_data' AIRFLOW_CTX_EXECUTION_DATE='2025-07-07T06:53:38.076557+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-07T06:53:38.076557+00:00'
[2025-07-07T07:16:46.739+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-07T07:16:46.745+0000] {baseoperator.py:399} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2025-07-07T07:16:46.752+0000] {python.py:237} INFO - Done. Returned value was: no_new_data_message
[2025-07-07T07:16:46.753+0000] {branch.py:36} INFO - Branch into no_new_data_message
[2025-07-07T07:16:46.753+0000] {skipmixin.py:178} INFO - Following branch no_new_data_message
[2025-07-07T07:16:46.764+0000] {skipmixin.py:246} INFO - Skipping tasks [('spark_write_data', -1)]
[2025-07-07T07:16:46.821+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-07T07:16:46.835+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=minio_ga4_new_file_detector, task_id=branch_if_new_data, execution_date=20250707T065338, start_date=20250707T071646, end_date=20250707T071646
[2025-07-07T07:16:46.862+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-07-07T07:16:46.914+0000] {taskinstance.py:3482} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-07-07T07:16:46.915+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
