[2025-07-07T07:19:57.740+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-07T07:19:57.756+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: minio_ga4_new_file_detector.branch_if_new_data manual__2025-07-07T06:53:38.076557+00:00 [queued]>
[2025-07-07T07:19:57.760+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: minio_ga4_new_file_detector.branch_if_new_data manual__2025-07-07T06:53:38.076557+00:00 [queued]>
[2025-07-07T07:19:57.760+0000] {taskinstance.py:2303} INFO - Starting attempt 4 of 5
[2025-07-07T07:19:57.765+0000] {taskinstance.py:2327} INFO - Executing <Task(BranchPythonOperator): branch_if_new_data> on 2025-07-07 06:53:38.076557+00:00
[2025-07-07T07:19:57.769+0000] {standard_task_runner.py:63} INFO - Started process 3972 to run task
[2025-07-07T07:19:57.771+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'minio_ga4_new_file_detector', 'branch_if_new_data', 'manual__2025-07-07T06:53:38.076557+00:00', '--job-id', '157', '--raw', '--subdir', 'DAGS_FOLDER/dag_automatic.py', '--cfg-path', '/tmp/tmp9xg29m2j']
[2025-07-07T07:19:57.772+0000] {standard_task_runner.py:91} INFO - Job 157: Subtask branch_if_new_data
[2025-07-07T07:19:57.780+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.11/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-07-07T07:19:57.801+0000] {task_command.py:426} INFO - Running <TaskInstance: minio_ga4_new_file_detector.branch_if_new_data manual__2025-07-07T06:53:38.076557+00:00 [running]> on host 34b334fe6b50
[2025-07-07T07:19:57.849+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='minio_ga4_new_file_detector' AIRFLOW_CTX_TASK_ID='branch_if_new_data' AIRFLOW_CTX_EXECUTION_DATE='2025-07-07T06:53:38.076557+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-07T06:53:38.076557+00:00'
[2025-07-07T07:19:57.850+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-07T07:19:57.857+0000] {baseoperator.py:399} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2025-07-07T07:19:57.865+0000] {python.py:237} INFO - Done. Returned value was: spark_write_data
[2025-07-07T07:19:57.865+0000] {branch.py:36} INFO - Branch into spark_write_data
[2025-07-07T07:19:57.865+0000] {skipmixin.py:178} INFO - Following branch spark_write_data
[2025-07-07T07:19:57.879+0000] {skipmixin.py:246} INFO - Skipping tasks [('no_new_data_message', -1)]
[2025-07-07T07:19:57.894+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-07T07:19:57.905+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=minio_ga4_new_file_detector, task_id=branch_if_new_data, execution_date=20250707T065338, start_date=20250707T071957, end_date=20250707T071957
[2025-07-07T07:19:57.942+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-07-07T07:19:57.962+0000] {taskinstance.py:3482} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-07-07T07:19:57.963+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
