[2025-07-07T07:27:27.659+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-07T07:27:27.678+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: minio_ga4_new_file_detector.branch_if_new_data manual__2025-07-07T06:53:38.076557+00:00 [queued]>
[2025-07-07T07:27:27.682+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: minio_ga4_new_file_detector.branch_if_new_data manual__2025-07-07T06:53:38.076557+00:00 [queued]>
[2025-07-07T07:27:27.682+0000] {taskinstance.py:2303} INFO - Starting attempt 6 of 7
[2025-07-07T07:27:27.687+0000] {taskinstance.py:2327} INFO - Executing <Task(BranchPythonOperator): branch_if_new_data> on 2025-07-07 06:53:38.076557+00:00
[2025-07-07T07:27:27.692+0000] {standard_task_runner.py:63} INFO - Started process 4494 to run task
[2025-07-07T07:27:27.694+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'minio_ga4_new_file_detector', 'branch_if_new_data', 'manual__2025-07-07T06:53:38.076557+00:00', '--job-id', '163', '--raw', '--subdir', 'DAGS_FOLDER/dag_automatic.py', '--cfg-path', '/tmp/tmpa9enxpzj']
[2025-07-07T07:27:27.695+0000] {standard_task_runner.py:91} INFO - Job 163: Subtask branch_if_new_data
[2025-07-07T07:27:27.703+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.11/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-07-07T07:27:27.727+0000] {task_command.py:426} INFO - Running <TaskInstance: minio_ga4_new_file_detector.branch_if_new_data manual__2025-07-07T06:53:38.076557+00:00 [running]> on host 34b334fe6b50
[2025-07-07T07:27:27.775+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='minio_ga4_new_file_detector' AIRFLOW_CTX_TASK_ID='branch_if_new_data' AIRFLOW_CTX_EXECUTION_DATE='2025-07-07T06:53:38.076557+00:00' AIRFLOW_CTX_TRY_NUMBER='6' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-07T06:53:38.076557+00:00'
[2025-07-07T07:27:27.776+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-07T07:27:27.781+0000] {baseoperator.py:399} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2025-07-07T07:27:27.787+0000] {python.py:237} INFO - Done. Returned value was: no_new_data_message
[2025-07-07T07:27:27.787+0000] {branch.py:36} INFO - Branch into no_new_data_message
[2025-07-07T07:27:27.787+0000] {skipmixin.py:178} INFO - Following branch no_new_data_message
[2025-07-07T07:27:27.799+0000] {skipmixin.py:246} INFO - Skipping tasks [('spark_write_data', -1)]
[2025-07-07T07:27:27.814+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-07T07:27:27.824+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=minio_ga4_new_file_detector, task_id=branch_if_new_data, execution_date=20250707T065338, start_date=20250707T072727, end_date=20250707T072727
[2025-07-07T07:27:27.865+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-07-07T07:27:27.886+0000] {taskinstance.py:3482} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-07-07T07:27:27.887+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
