[2025-07-04T02:27:05.432+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-04T02:27:05.449+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: connect_to_minio.download_one_file scheduled__2025-07-03T00:00:00+00:00 [queued]>
[2025-07-04T02:27:05.455+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: connect_to_minio.download_one_file scheduled__2025-07-03T00:00:00+00:00 [queued]>
[2025-07-04T02:27:05.455+0000] {taskinstance.py:2303} INFO - Starting attempt 14 of 14
[2025-07-04T02:27:05.461+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): download_one_file> on 2025-07-03 00:00:00+00:00
[2025-07-04T02:27:05.465+0000] {standard_task_runner.py:63} INFO - Started process 944 to run task
[2025-07-04T02:27:05.467+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'connect_to_minio', 'download_one_file', 'scheduled__2025-07-03T00:00:00+00:00', '--job-id', '95', '--raw', '--subdir', 'DAGS_FOLDER/test_connection_to_minio.py', '--cfg-path', '/tmp/tmpop4ygi5v']
[2025-07-04T02:27:05.468+0000] {standard_task_runner.py:91} INFO - Job 95: Subtask download_one_file
[2025-07-04T02:27:05.478+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.11/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-07-04T02:27:05.498+0000] {task_command.py:426} INFO - Running <TaskInstance: connect_to_minio.download_one_file scheduled__2025-07-03T00:00:00+00:00 [running]> on host a419d8548e77
[2025-07-04T02:27:05.543+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='connect_to_minio' AIRFLOW_CTX_TASK_ID='download_one_file' AIRFLOW_CTX_EXECUTION_DATE='2025-07-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='14' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-03T00:00:00+00:00'
[2025-07-04T02:27:05.543+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-04T02:27:05.891+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-04T02:27:05.891+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/test_connection_to_minio.py", line 135, in download_one_file
    client.download_file(bucket_name, obj_key, local_path)
  File "/home/airflow/.local/lib/python3.11/site-packages/boto3/s3/inject.py", line 192, in download_file
    return transfer.download_file(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/boto3/s3/transfer.py", line 405, in download_file
    future.result()
  File "/home/airflow/.local/lib/python3.11/site-packages/s3transfer/futures.py", line 103, in result
    return self._coordinator.result()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/s3transfer/futures.py", line 266, in result
    raise self._exception
  File "/home/airflow/.local/lib/python3.11/site-packages/s3transfer/tasks.py", line 139, in __call__
    return self._execute_main(kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/s3transfer/tasks.py", line 162, in _execute_main
    return_value = self._main(**kwargs)
                   ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/s3transfer/download.py", line 642, in _main
    fileobj.seek(offset)
  File "/home/airflow/.local/lib/python3.11/site-packages/s3transfer/utils.py", line 387, in seek
    self._open_if_needed()
  File "/home/airflow/.local/lib/python3.11/site-packages/s3transfer/utils.py", line 370, in _open_if_needed
    self._fileobj = self._open_function(self._filename, self._mode)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/s3transfer/utils.py", line 281, in open
    return open(filename, mode)
           ^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/downloads/data_example.parquet.dd82e06D'
[2025-07-04T02:27:05.902+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=connect_to_minio, task_id=download_one_file, execution_date=20250703T000000, start_date=20250704T022705, end_date=20250704T022705
[2025-07-04T02:27:05.918+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 95 for task download_one_file ([Errno 2] No such file or directory: '/opt/airflow/downloads/data_example.parquet.dd82e06D'; 944)
[2025-07-04T02:27:05.960+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-07-04T02:27:05.974+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-04T02:27:05.975+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
