[2025-07-08T10:02:13.128+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-08T10:02:13.146+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: minio_ga4_new_file_detector.branch_if_new_data manual__2025-07-08T09:39:19.707078+00:00 [queued]>
[2025-07-08T10:02:13.149+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: minio_ga4_new_file_detector.branch_if_new_data manual__2025-07-08T09:39:19.707078+00:00 [queued]>
[2025-07-08T10:02:13.149+0000] {taskinstance.py:2303} INFO - Starting attempt 3 of 4
[2025-07-08T10:02:13.154+0000] {taskinstance.py:2327} INFO - Executing <Task(BranchPythonOperator): branch_if_new_data> on 2025-07-08 09:39:19.707078+00:00
[2025-07-08T10:02:13.158+0000] {standard_task_runner.py:63} INFO - Started process 9628 to run task
[2025-07-08T10:02:13.162+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'minio_ga4_new_file_detector', 'branch_if_new_data', 'manual__2025-07-08T09:39:19.707078+00:00', '--job-id', '188', '--raw', '--subdir', 'DAGS_FOLDER/dag_automatic.py', '--cfg-path', '/tmp/tmpvg20p1st']
[2025-07-08T10:02:13.164+0000] {standard_task_runner.py:91} INFO - Job 188: Subtask branch_if_new_data
[2025-07-08T10:02:13.173+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.11/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-07-08T10:02:13.194+0000] {task_command.py:426} INFO - Running <TaskInstance: minio_ga4_new_file_detector.branch_if_new_data manual__2025-07-08T09:39:19.707078+00:00 [running]> on host 1a66de7e9daf
[2025-07-08T10:02:13.237+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='minio_ga4_new_file_detector' AIRFLOW_CTX_TASK_ID='branch_if_new_data' AIRFLOW_CTX_EXECUTION_DATE='2025-07-08T09:39:19.707078+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-08T09:39:19.707078+00:00'
[2025-07-08T10:02:13.237+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-08T10:02:13.242+0000] {baseoperator.py:399} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2025-07-08T10:02:13.248+0000] {python.py:237} INFO - Done. Returned value was: spark_write_data
[2025-07-08T10:02:13.248+0000] {branch.py:36} INFO - Branch into spark_write_data
[2025-07-08T10:02:13.248+0000] {skipmixin.py:178} INFO - Following branch spark_write_data
[2025-07-08T10:02:13.260+0000] {skipmixin.py:246} INFO - Skipping tasks [('no_new_data_message', -1)]
[2025-07-08T10:02:13.272+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-08T10:02:13.282+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=minio_ga4_new_file_detector, task_id=branch_if_new_data, execution_date=20250708T093919, start_date=20250708T100213, end_date=20250708T100213
[2025-07-08T10:02:13.332+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-07-08T10:02:13.358+0000] {taskinstance.py:3482} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-07-08T10:02:13.359+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
